### PR TITLE
Footer link style fix and fix for a small margin at the very bottom

### PR DESCRIPTION
**Pull request by adri326**
I know I'm surelly annoying with all thos PRs, but fixing your messy style chills me 😜

### CODE REVIEW

**Review by zspri — APPROVED** [review]
Looks good!

**Comment by coke11** [comment]
@adri326 @NaturalmotionStudios I have now added @adri326 to the Github, so if they want to make edits they no longer have to make a PR.

**Comment by zspri** [comment]
@coke11 Ok

**Comment by adri326** [comment]
Thanks!

**Pull request merged**
