### PR TITLE
Added the scratch user verification message

### PR DESCRIPTION
**Pull request by adri326**
Warning! I just implemented the feature as said in this discussion:

https://github.com/dragon-drop-scratch/dragon-drop-www/issues/20#issuecomment-248752537/

We should filter the username to prevent an user to write something that isn't valid. Additionally, we could add a "does he exists?" GET request to the scratch API to be sure he wrote something right.

And, I don't have the write access, sorry :/

### CODE REVIEW

**Comment by zspri** [comment]
One of the execs will give you write access.

@coke11 @golden-scratch

**Comment by coke11** [comment]
I thought I did. I put him on the @dragon-drop-scratch/helpers team...

**Comment by coke11** [comment]
@adri326 Can you accept your invite?

**Comment by adri326** [comment]
Accepted, thanks!

**Comment by zspri** [comment]
@adri326 Welcome to the DragonDrop team!

**Comment by coke11** [comment]
@adri326 Yes! You are doing a great job so far :) @NaturalmotionStudios Would you mind getting on Gitter?

**Comment by zspri** [comment]
@coke11 ok :)

**Pull request merged**
