### PR TITLE
Updated <head> tag

### PR DESCRIPTION
**Pull request by csf30816**

### CODE REVIEW

**Comment by coke11** [comment]
Hm. It won't let me merge....

**Comment by Sheshank-s** [comment]
Hmmm... favicon isn't popping up?

**Comment by coke11** [comment]
I think I was able to do it without a merge. Let me know if I did it right

**Comment by csf30816** [comment]
Ok, every thing is right exept for in the middle of the <head tag there is an extra </head tag, please get rid of that , so it will work. Thanks

**Comment by Sheshank-s** [comment]
Ok great! It's funny that all our problems are because of the head tags!

**Comment by csf30816** [comment]
:)

**Comment by coke11** [comment]
Fixed

**Pull request closed without merging**
